name: Build

env:
  DOTNET_VERSION: "10.0.x"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Source/**"
      - "Specs/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "Source/**"
      - "Specs/**"

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build
